import jsPDF from 'jspdf';

export interface GeneratePDFParams {
    title: string;
    videoUrl: string;
    summary: string;
    summaryType?: string;
    language?: string;
}

export function generateSummaryPDF({
    title,
    videoUrl,
    summary,
    summaryType,
    language
}: GeneratePDFParams): string {
    const doc = new jsPDF();

    // Page dimensions
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - (margin * 2);

    let yPosition = margin;

    // Helper function to add text with word wrap
    const addText = (text: string, fontSize: number, fontStyle: 'normal' | 'bold' = 'normal', color: [number, number, number] = [0, 0, 0]) => {
        doc.setFontSize(fontSize);
        doc.setFont('helvetica', fontStyle);
        doc.setTextColor(color[0], color[1], color[2]);

        const lines = doc.splitTextToSize(text, maxWidth);

        for (const line of lines) {
            // Check if we need a new page
            if (yPosition + fontSize / 2 > pageHeight - margin) {
                doc.addPage();
                yPosition = margin;
            }

            doc.text(line, margin, yPosition);
            yPosition += fontSize / 2 + 2;
        }

        yPosition += 5; // Add spacing after paragraph
    };

    // Title
    addText(title, 18, 'bold', [33, 37, 41]);
    yPosition += 5;

    // Metadata section
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;

    // Video URL
    addText('Video URL:', 10, 'bold', [100, 100, 100]);
    yPosition -= 5;
    doc.setTextColor(59, 130, 246); // Blue color for link
    doc.textWithLink(videoUrl, margin, yPosition, { url: videoUrl });
    doc.setFontSize(10);
    const urlLines = doc.splitTextToSize(videoUrl, maxWidth);
    yPosition += (urlLines.length * 6) + 10;

    // Summary Type
    if (summaryType) {
        addText(`Summary Type: ${summaryType.charAt(0).toUpperCase() + summaryType.slice(1)}`, 10, 'normal', [100, 100, 100]);
    }

    // Language
    if (language && language !== 'auto') {
        addText(`Language: ${language.toUpperCase()}`, 10, 'normal', [100, 100, 100]);
    }

    yPosition += 5;
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 15;

    // Summary heading
    addText('Summary', 14, 'bold', [33, 37, 41]);
    yPosition += 5;

    // Summary content - split by paragraphs
    const paragraphs = summary.split('\n\n');

    for (const paragraph of paragraphs) {
        if (paragraph.trim()) {
            // Check if it's a heading (starts with # or **)
            if (paragraph.trim().startsWith('#')) {
                const headingText = paragraph.replace(/^#+\s*/, '').trim();
                addText(headingText, 12, 'bold', [33, 37, 41]);
            } else if (paragraph.trim().startsWith('**')) {
                const headingText = paragraph.replace(/\*\*/g, '').trim();
                addText(headingText, 11, 'bold', [33, 37, 41]);
            } else {
                // Regular paragraph - handle bullet points
                const lines = paragraph.split('\n');
                for (const line of lines) {
                    if (line.trim().startsWith('-') || line.trim().startsWith('•')) {
                        const bulletText = '  • ' + line.replace(/^[-•]\s*/, '').trim();
                        addText(bulletText, 10, 'normal', [33, 37, 41]);
                    } else if (line.trim()) {
                        addText(line.trim(), 10, 'normal', [33, 37, 41]);
                    }
                }
            }
        }
    }

    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `Generated by Summ-it • Page ${i} of ${totalPages}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
    }

    // Return base64 encoded PDF
    return doc.output('datauristring');
}
